---
name: SpigotSystemd
website: https://git.revreso.de/gigadoc2/spigot-systemd
description: Integrates Spigot with systemd when running as a systemd service.
author: Gigadoc2
version: 1.0.0

main: jetzt.nicht.SpigotSystemd.SpigotSystemd
load: STARTUP
